# Generated by Django 6.1.1 on 2026-09-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='education',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
