# Generated by Django 6.1.1 on 2026-10-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='projects',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
