# Generated by Django 6.1.1 on 2026-10-01 02:33

from django.db import migrations, models


def normalize_to_lists(apps, schema_editor):
    UserInfo = apps.get_model("core", "UserInfo")
    for obj in UserInfo.objects.all():
        changed = False
        for field_name in ("education", "projects"):
            value = getattr(obj, field_name)
            if value is None:
                continue
            if isinstance(value, dict):
                # {} -> [], {…} -> [{…}]
                setattr(obj, field_name, [] if not value else [value])
                changed = True
        if changed:
            obj.save(update_fields=["education", "projects"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userinfo_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='education',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='projects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(normalize_to_lists, reverse_noop),
    ]
