# Generated by Django 6.1.1 on 2026-10-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userinfo_education_alter_userinfo_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='contact_information',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
